# Generated by Django 5.0.2 on 2024-02-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
