# Generated by Django 4.2.5 on 2024-02-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="links",
        ),
        migrations.AddField(
            model_name="link",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.page",
            ),
        ),
    ]
