# Generated by Django 4.2.5 on 2024-02-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_page_links_link_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
